### ISSUE TITLE
Implement difficulty levels for singleplayer (vs AI)

### ISSUE THREAD

**Issue by mebn** [mebn/pong_is1500#19]

**Comment by mebn** [comment]
Maybe something like this

EASY: p2 follows ball with delay (1s?)
NORMAL: EASY + faster ball
HARD: NORMAL + delay (<0.5s?)
IMPOSSIBLE: P2 is a wall. Impossible to win

**Comment by alexarne** [comment]
alternative 1 (speed modification):
EASY: follows the ball's y-pos but paddle has slow speed
NORMAL: follows the ball's y-pos and paddle has normal/high speed
HARD: calculates where the ball will end up and moves there (slow speed)
IMPOSSIBLE: calculates where the ball will end up and moves there (fast speed)

alternative 2 (no differing speeds between human and AI paddles):
EASY: human player's paddle is a wall (can't lose)
NORMAL: follows the ball's y-pos (same speed as human player's padle)
HARD: predicts by equations where the ball will end up and places paddle there
IMPOSSIBLE: AI's paddle is a wall (can't lose)

**Comment by alexarne** [comment]
either way, refactor into a function call for ai control with respect to difficulty, do not handle in game update loop directly
